### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by Suntrie** [mishkowsky/Grep#1]
1. Все ли флаги утилиты являются совместимыми между собой?

**Comment by Suntrie** [comment]
Решение с CASE_INSENSITIVE выглядит достаточно интересно. Является ли оно универсальным (в текущей версии; какие есть ограничения)?

**Comment by mishkowsky** [comment]
Поддержка Unicode добавлена с помощью флага Pattern.UNICODE_CASE.
